### ISSUE TITLE
Suport for NSNumberFormatter

### ISSUE THREAD

**Issue by JeanChRocha** [dataxpress/UICountingLabel#46]
I didn't get how to use with NSNumberFormatterCurrencyStyle, is it possible? how?

**Comment by rjpalermo1** [comment]
Sadly, I'm having the same issue.  I see this post was 10 months ago - if dataexpress still exists here is what I'm trying with no luck:

```
			_lblAvgSaleAmt = [[UICountingLabel alloc] init]; //IBOutlet label subclassed
			NSNumberFormatter *n1 = [[NSNumberFormatter alloc] init];
			[n1 setNumberStyle:NSNumberFormatterCurrencyStyle];
			n1.locale = [NSLocale currentLocale];
			int L1 = [avgSale integerValue]; //avgSale is a dynamic NSNumber
			
			_lblAvgSaleAmt.formatBlock = ^NSString* (CGFloat avgSale) {
				return [n1 stringFromNumber:@((int)avgSale)];
			};
			_lblAvgSaleAmt.method = UILabelCountingMethodEaseOut;
			[_lblAvgSaleAmt countFrom:0 to:L1 withDuration:2.5];
```

**Comment by dataxpress** [comment]
I noticed in this line: 

    _lblAvgSaleAmt = [[UICountingLabel alloc] init]; //IBOutlet label subclassed

The comment is concerning because it looks like you are hooking up the UICountingLabel with an IBOutlet and then calling `[[UICountingLabel alloc] init]` again and replacing the ivar without adding it to the view. Is this line actually in your code or is it just for demonstration purposes?

Also, what is the actual problem you're having? Is the label not counting at all? Is the format showing up wrong? Can you even see the label?

Thanks,
Tim

**Comment by rjpalermo1** [comment]
HI Tim thanks for responding.  

I will need to go back and retry this in my project.  I backed it out and just went with a fade in effect.  Give me a couple days and I'll get back.

Merry Christmas!
